version: "3"

services:
  sniperbot:
    build: .
    entrypoint: python main.py
    volumes:
       - ./main.py:/SniperCallsbot/main.py
       - ./logs:/SniperCallsbot/logs
       - ./backtesting:/SniperCallsbot/backtesting
       - ./tentacles:/SniperCallsbot/tentacles
       - ./user:/SniperCallsbot/user
       - ./static:/SniperCallsbot/static
    ports:
       - 5000:5000
    restart: always
  
  # watchtower:
  #   image: containrrr/watchtower
  #   restart: always
  #   command: --cleanup --include-restarting
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
